### ISSUE TITLE
Send negative values

### ISSUE THREAD

**Issue by haitham-khairy** [EmbeddedSam/Modbus-Slave-for-PIC18F#8]
Hellow

how can i send a float number 5.4 or negative number -4
i trying to put them in holding register but only send unsigned intger numbers to kep server

**Comment by Zaaphod** [comment]
as far as I know the modbus standard does not allow direct sending of anything other than unsigned integers into registers.  There are a number of schemes out there to get around this.. for example you could use register 3 for the numeric part of a number than use coil 3 to represent the sign of the number stored in register 3.   For floating point it is common to multiply the number by a factor large enough to get rid of the decimal and the new number in one register then send the factor in another.  so you could do 5.4 X 100 = 540 send the 540 in one register and the 100 in another register.   For really large numbers you need to break them down into high words and low words and send them interdependently.    

Here's a link I found doing a quick search:
http://digital.ni.com/public.nsf/allkb/AD8172B710AFB13F86257974007D6F52

hope this helps

**Comment by paucoma** [comment]
Hi haitham-khairy, 
Basic Modbus provides function codes that define Reading and/or Writing of either a single bit, a series of single bits, a 16-bit word or a series of 16-bit word registers. 
What these bits respresent is dependent on another processing level of the application. 
Since you mentioned previously that you are going to have your device communicating with some PLCs, you should have a look at how these PLCs implement the transmission/reception of negative and floating point numbers and adapt your implementation to this. 
As Zaaphod mentioned, there are a number of Schemes, I would recommend using the [Two's Complement](https://en.wikipedia.org/wiki/Two%27s_complement) with scaling as it allows for easy arithmetic and comparison operations on the numbers, but as I mentioned previously : if you are going to be working with other already existing devices, you are going to need to implement what they already understand to be compatible.
Cheers

**Comment by haitham-khairy** [comment]
Thanks For your help
